/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'gabriel.sideri' at '10/31/16 11:14 AM' with Gradle 2.14
 *
 * @author gabriel.sideri, @date 10/31/16 11:14 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
